version: '8.13.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"

  llm_app:
    build: .
    volumes:
      - "C:/Users/yonzb/OneDrive/Documents/Ai_Projects/Partner_Local_Ai/MiniLM/paraphrase-multilingual-MiniLM-L12-v2:/model"
    depends_on:
      - elasticsearch
    ports:
      - "5000:80"
